/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   lexer_set_args.c                              :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ibertran <ibertran@student.42lyon.fr>      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/03/04 23:54:48 by ibertran          #+#    #+#             */
/*   Updated: 2024/03/05 00:06:17 by ibertran         ###   ########lyon.fr   */
/*                                                                            */
/* ************************************************************************** */

#include "lexer.h"

/*
	DESCRIPTION
	The lexer_set_args() function iterate through the tokens generated by
	the lexer. Once a command token is encoutered, it assign the _ARG_TOK
	type to every consecutive command token. When an operator or a round
	bracket token is encoutered, it goes back to it's initial behaviour.

	RETURN VALUE
	The clexer_set_args() function return no value.
*/

void	lexer_set_args(t_vector *lexer)
{
	t_lexer_token	*tok;
	int				index;
	int				status;

	status = 0;
	index = 0;
	tok = ft_vector_get(lexer, index++);
	while (tok)
	{
		if (tok->type == _CMD_TOK)
		{
			if (!status)
				status = 1;
			else
				tok->type = _ARG_TOK;
		}
		if (tok->type <= _PIPE_TOK
			|| tok->type == _OPEN_BRACKETS_TOK
			|| tok->type == _CLOSE_BRACKETS_TOK)
			status = 0;
		tok = ft_vector_get(lexer, index++);
	}
}
